# Generated by Django 4.1.7 on 2023-03-30 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0004_ingredient_ingredient_uniq_name_amount_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="cooks",
            field=models.ManyToManyField(
                related_name="dishes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="dishes", to="kitchen.ingredient"
            ),
        ),
    ]
