# Generated by Django 4.0.2 on 2023-03-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_alter_dish_cooks_alter_dish_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='dishtype',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', to='kitchen.Ingredient'),
        ),
    ]
